=== hjianping/DuoDuo/ProjectInit/src/main/resources/xsd/DbEntityList.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:entity="https://github.com/qiunet/DuoDuo/DbEntityList"
		   xmlns:base="https://github.com/qiunet/DuoDuo/Base"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="https://github.com/qiunet/DuoDuo/DbEntityList"
		   elementFormDefault="qualified"
>
	<xs:import namespace="https://github.com/qiunet/DuoDuo/Base" schemaLocation="Base.xsd" />

	<xs:complexType name="constructor_content">
		<xs:sequence>
			<xs:element name="constructor_arg" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:attribute name="field" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="db_entity_list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="field" minOccurs="2" maxOccurs="unbounded" type="base:field_content" />
				<xs:element name="constructor" minOccurs="0" maxOccurs="5" type="entity:constructor_content"/>
			</xs:sequence>
			<xs:attributeGroup ref="base:EntityListAttributeGroup" />
		</xs:complexType>

		<xs:unique name="field_name_unique">
			<xs:annotation>
				<xs:documentation>field 的 name字段必须唯一不重复 </xs:documentation>
			</xs:annotation>
			<xs:selector xpath="entity:field"/>
			<xs:field xpath="@name"/>
		</xs:unique>

		<xs:key name="key_of_field_name">
			<xs:annotation>
				<xs:documentation>将field的name作为id, 以便其它地方引用</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="entity:field"/>
			<xs:field xpath="@name"/>
		</xs:key>

		<xs:keyref name="constructor_arg的field字段" refer="entity:key_of_field_name">
			<xs:annotation>
				<xs:documentation>对 constructor 的 constructor-arg 的 field 属性进行约束</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="entity:constructor/entity:constructor_arg" />
			<xs:field xpath="@field" />
		</xs:keyref>

		<xs:keyref name="entity的key字段" refer="entity:key_of_field_name">
			<xs:annotation>
				<xs:documentation>对 entity 的 key属性进行约束</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="." />
			<xs:field xpath="@key" />
		</xs:keyref>

		<xs:keyref name="entity的subKey字段" refer="entity:key_of_field_name">
			<xs:annotation>
				<xs:documentation>对 entity 的 subkey属性进行约束</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="." />
			<xs:field xpath="@subKey" />
		</xs:keyref>
	</xs:element>
</xs:schema>

=== hjianping/DuoDuo/ProjectInit/src/test/resources/xml/item.xml
<?xml version="1.0" encoding="UTF-8"?>
<db_entity_list key="uid"
				subKey="item_id"
				name="ItemDo"
				baseDir="src/test/java"
				packageName="org.qiunet.project.init.test.item"
				xmlns="https://github.com/qiunet/DuoDuo/DbEntityList"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation="https://github.com/qiunet/DuoDuo/DbEntityList
				https://raw.githubusercontent.com/qiunet/DuoDuo/master/ProjectInit/src/main/resources/xsd/DbEntityList.xsd"
	>
	<field name="uid" type="long" comment="玩家id" />
	<field name="item_id" type="int" comment="道具id" />
	<field name="count" type="int" comment="数量"/>
	<constructor>
		<constructor_arg field="uid"/>
	</constructor>
	<constructor>
		<constructor_arg field="uid" />
		<constructor_arg field="item_id" />
	</constructor>
</db_entity_list>
