<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE base[
        <!ELEMENT base (entity+) >
        <!ATTLIST base baseDir CDATA #REQUIRED>
        <!ATTLIST base vmfilePath CDATA #REQUIRED>
        <!ATTLIST base filePostfix CDATA #REQUIRED>
        <!ELEMENT entity (field+) >
        <!ATTLIST entity name ID #REQUIRED>
        <!ATTLIST entity dbInfoKey NMTOKEN #REQUIRED>
        <!ATTLIST entity packagePath NMTOKEN #REQUIRED>
        <!ATTLIST entity entityType (PlatformRedisList|RedisList|RedisEntity|PlatformRedisEntity) #REQUIRED>
        <!ATTLIST entity subKey CDATA "">
        <!ELEMENT field EMPTY>
        <!ATTLIST field name NMTOKEN #REQUIRED>
        <!ATTLIST field type (int|String|Date|long) #REQUIRED>
        <!ATTLIST field comment CDATA #REQUIRED>
]>

<base baseDir="src/test/java" vmfilePath="vm/entity_create.vm" filePostfix="java">
    <entity name="EquipPo" dbInfoKey="uid" subKey="id" packagePath="org.qiunet.template.equip.entity" entityType="PlatformRedisList">
        <field name="uid" type="int" comment="uid " />
        <field name="id" type="int" comment="设定id" />
        <field name="exp" type="int" comment="经验" />
        <field name="level" type="int" comment="等级" />
    </entity>

    <entity name="SysmsgPo" dbInfoKey="uid" subKey="id" packagePath="org.qiunet.template.sysmsg.entity" entityType="RedisList" >
        <field name="id" type="int" comment="id " />
        <field name="uid" type="int" comment="uid " />
        <field name="msg" type="String" comment="消息体" />
        <field name="param" type="String" comment="参数" />
    </entity>

    <entity name="FriendPo" dbInfoKey="uid" packagePath="org.qiunet.template.friend.entity" entityType="RedisEntity">
        <field name="uid" type="int" comment="uid " />
        <field name="friend_descs" type="String" comment="好友的字符串" />
    </entity>

    <entity name="PlayerPo" dbInfoKey="uid" packagePath="org.qiunet.template.player.entity" entityType="PlatformRedisEntity">
        <field name="uid" type="int" comment="uid " />
        <field name="exp" type="int" comment="经验" />
        <field name="level" type="int" comment="等级" />
    </entity>

    <entity name="LoginPo" dbInfoKey="openid" packagePath="org.qiunet.template.login.entity" entityType="RedisEntity">
        <field name="openid" type="String" comment="openId" />
        <field name="uid" type="int" comment="uid " />
        <field name="token" type="String" comment="openID 对应的 token" />
    </entity>

    <entity name="GlobalTablePo" dbInfoKey="id" packagePath="org.qiunet.template.global.entity" entityType="RedisEntity">
        <field name="id" type="int" comment="id" />
        <field name="name" type="String" comment="名称" />
    </entity>

    <entity name="ItemPo" dbInfoKey="uid" packagePath="org.qiunet.template.item.entity" entityType="RedisList" subKey="item_id">
        <field name="uid" type="int" comment="uid"/>
        <field name="item_id" type="int" comment="道具id"/>
        <field name="item_count" type="int" comment="道具数量"/>
    </entity>

    <entity name="QunxiuPo" dbInfoKey="id" packagePath="org.qiunet.template.qunxiu.entity" entityType="RedisEntity" >
        <field name="id" type="int" comment="id" />
        <field name="name" type="String" comment="名称" />
        <field name="master" type="int" comment="主管uid" />
        <field name="level" type="int" comment="等级" />
    </entity>
</base>
